name: DNS Tunnel Server Host

on:
  workflow_dispatch:

jobs:
  run-dns-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Update CloudDNS with Current Runner IP
        run: |
          RESPONSE=$(curl -s "${{ secrets.CLOUDDNS_DYNAMIC_URL }}")
          echo "CloudDNS Updated: $RESPONSE"

      - name: Install Dependencies & dnstt
        run: |
          sudo apt-get update && sudo apt-get install -y wget git golang psmisc
          git clone https://www.bamsoftware.com/git/dnstt.git
          cd dnstt/dnstt-server
          go build

      - name: Generate Keys
        run: |
          cd dnstt/dnstt-server
          ./dnstt-server -gen-key -privkey-file server.key -pubkey-file server.pub
          echo "=== PUBLIC KEY (Copy this to your Client) ==="
          cat server.pub
          echo "============================================="

      - name: Free Port 53 and Run dnstt Server
        run: |
          cd dnstt/dnstt-server
          
          # إيقاف الخدمة الحاجزة للـ Port 53
          sudo systemctl stop systemd-resolved
          sudo systemctl disable systemd-resolved
          sudo fuser -k 53/udp || true
          
          # تشغيل السيرفر
          sudo ./dnstt-server -udp :53 -privkey-file server.key test.mureyad.duckdns.org 127.0.0.1:22
